### ISSUE TITLE
Ignoring the read status when exporting to BibTex /BibLaTex

### ISSUE THREAD

**Issue by dleporis** [Dominic-DallOsto/zotero-reading-list#6]
I tried the add-on and it is great, but I don't need the read status to be displayed in the output PDF.  Is it possible to remove the read status in the output from Zotero (so that I can see it as a user, but it is not exported to BibTex / BibLaTex)?
I am using Overleaf which is able to sync Zotero bibliography.

Here is the current bibliography of my output PDF (**problematic parts in bold**):

Bibliography
[1] D. Osokin, “Real-time 2d multi-person pose estimation on CPU: Lightweight OpenPose,” 2018,
Publisher: arXiv Version Number: 1 **Read_Status: To Read Read_Status_Date: 2023-02-16T14:04:41.638Z**.
DOI: 10.48550/ARXIV.1811.12004. [Online]. Available: https://arxiv.org/abs/
1811.12004 (visited on 02/16/2023).
[2] E. T. Hall, The hidden dimension. New York: Anchor Books, 1990, 217 pp., **Read_Status: To Read
Read_Status_Date: 2023-02-16T16:00:08.414Z**, ISBN: 978-0-385-08476-5.

**Comment by Dominic-DallOsto** [comment]
Thanks a lot! This definitely shouldn't be exported to Bibtex - I'll check this out

**Comment by skjelanger** [comment]
I know this issue already has been resolved in v1.1.0, but as Zotero 6 is still the latest stable official release of Zotero, is it possible to to implement this fix to the v0.3.2 (which is the last Zotero 6 compatible version) ?

**Comment by JMourisca** [comment]
The problem is still there. 

![image](https://github.com/Dominic-DallOsto/zotero-reading-list/assets/30648/b55223c7-a8c5-4a11-a536-e089352bf44a)

![image](https://github.com/Dominic-DallOsto/zotero-reading-list/assets/30648/8646a3d8-3d93-4796-880e-fc78462eab7a)

**Comment by Dominic-DallOsto** [comment]
Hey sorry, I'm not able to reproduce this when using the same version of Zotero Reading List and any of the Better Bibtex exporters.

Can you tell me more detailed steps for how you exported the citation? And show the .bib file that gets exported?

Thanks!

**Comment by skjelanger** [comment]
> Can you tell me more detailed steps for how you exported the citation? Are you using the "export" option from Zotero or some other method? And can you show the .bib file that gets exported?

I get this issue when syncing the library directly with Overleaf, and using biblatex. The format of the exportet .bib file is like this: 

```
@article{actor_data-driven_2024,
	title = {Data-driven Whitney forms for structure-preserving control volume analysis},
	volume = {496},
	issn = {0021-9991},
	url = {...},
	doi = {10.1016/j.jcp.2023.112520},
	abstract = {...},
	pages = {112520},
	journaltitle = {Journal of Computational Physics},
	shortjournal = {Journal of Computational Physics},
	author = {Actor, Jonas A. and Hu, Xiaozhe and Huang, Andy and Roberts, Scott A. and Trask, Nathaniel},
	date = {2024-01-01},
	note = {Read\_Status: In Progress
Read\_Status\_Date: 2024-06-24T07:27:24.312Z},
	keywords = {Whitney forms},
}
```


The problem is therefore the read status being exportet as 'note', which by default is displayed for \printbibliography. It can be circumvented using 
`\AtEveryBibitem{\clearfield{note}}`

**Comment by Dominic-DallOsto** [comment]
Ahh perfect, thanks. I only modified the output of Zotero's "export" function but I guess Overleaf syncing uses a different method that I didn't catch.
